//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloOnline.Research.Launcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://primary.updates.anvilonline.net/update.json</string>
  <string>https://secondary.updates.anvilonline.net/update.json</string>
  <string>https://tertiary.updates.anvilonline.net/update.json</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UpdateServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UpdateServers"]));
            }
            set {
                this["UpdateServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>https://primary.auth.anvilonline.net/</string>
  <string>https://secondary.auth.anvilonline.net/</string>
  <string>https://tertiary.auth.anvilonline.net/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AuthServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AuthServers"]));
            }
            set {
                this["AuthServers"] = value;
            }
        }
    }
}
